/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.employeepayroll;

import org.junit.Test;

import com.bridgelabz.employeepayroll.EmployeePayrollData;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        EmployeePayrollData classUnderTest = new EmployeePayrollData();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
