/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.employeepayroll;

import org.junit.Assert;
import org.junit.Test;

import com.bridgelabz.employeepayroll.EmployeePayrollData;

import static org.junit.Assert.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.IntStream;

public class NIOFileAPITest {
	private static String HOME = System.getProperty("user.home");
	private static String PLAY_WITH_NIO="TempPlayGround";
	
    @Test public void givenPath_performFileOperations_Confirm() {
        //Check file Exists
    	Path homePath=Paths.get(HOME);
        Assert.assertTrue(Files.exists(homePath));
        
        //Delete File and Check File Not Exist
        Path playPath=Paths.get(HOME+"/"+PLAY_WITH_NIO);
        if(Files.exists(playPath))
        	FileUtils.deleteFiles(playPath.toFile());
        Assert.assertTrue(Files.notExists(playPath));
        
        //Create Directory
        try {
			Files.createDirectories(playPath);
		} catch (IOException e) {
			e.printStackTrace();
		}
        Assert.assertTrue(Files.exists(playPath));
        
        //Create File
        IntStream.range(1, 10).forEach(counter -> {
        	Path tempFile=Paths.get(playPath + "/temp"+counter);
        	Assert.assertTrue(Files.notExists(tempFile));
        	try {
        		Files.createFile(tempFile);
        	}catch(IOException e) {
        		Assert.assertTrue(Files.exists(tempFile));
        	}
        });
    }
}
